/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_DSE_dse0 0x00u         /*!<@brief Drive Strength Enable: Low */
#define PCR_IBE_ibe1 0x01u         /*!<@brief Input Buffer Enable: Enables */
#define PCR_INV_inv0 0x00u         /*!<@brief Invert Input: Does not invert */
#define PCR_ODE_ode0 0x00u         /*!<@brief Open Drain Enable: Disables */
#define PCR_PE_pe0 0x00u           /*!<@brief Pull Enable: Disables */
#define PCR_PFE_pfe0 0x00u         /*!<@brief Passive Filter Enable: Disables */
#define PCR_PS_ps0 0x00u           /*!<@brief Pull Select: Enables internal pulldown resistor */
#define PCR_PV_pv0 0x00u           /*!<@brief Pull Value: Low */
#define PCR_SRE_sre0 0x00u         /*!<@brief Slew Rate Enable: Fast */
#define PORT2_PCR4_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT1_9 (number 3), I3C_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I3C_SCL_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I3C_SCL_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I3C_SCL_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_8 (number 2), I3C_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_I3C_SDA_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_I3C_SDA_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_I3C_SDA_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT3_12 (number 38), LED_RED
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_RED_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_13 (number 37), LED_GREEN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT3_0 (number 46), LED_BLUE
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BLUE_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT2_4 (number 18), ALERT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ALERT_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ALERT_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ALERT_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ALERT_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ALERT_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ALERT_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
